### ISSUE TITLE
panic: illegal base64 data at input byte 436512

### ISSUE THREAD

**Issue by moqmar** [markbates/pkger#116]
I'm trying to bundle [RemixIcon](https://remixicon.com/) with my application, but adding any of the binary font files (eot, ttf, woff2) results in the following panic when trying to start the compiled application:
```
app_1       | panic: illegal base64 data at input byte 436512
app_1       | 
app_1       | goroutine 1 [running]:
app_1       | github.com/markbates/pkger.Apply(0xf09f80, 0x0, 0xef5c20, 0xc0001a61b0, 0x0, 0x0)
app_1       |   /go/pkg/mod/github.com/markbates/pkger@v0.17.0/apply.go:12 +0x13a
app_1       | codeberg.org/zottelchin/vocab/internal.init()
app_1       |   /app/internal/pkged.go:12 +0xb9
```

**Comment by requaos** [comment]
Possible duplicate of #26

**Comment by ItalyPaleAle** [comment]
I have the same issue when building a binary similar to what @moqmar has, including a binary file (a font).

Weirdly, the issue does NOT seem to happen when I'm compiling the app on macOS. However, in the CI server (which uses the official Go Docker image on Linux Alpine) it does happen in at least the binaries for Linux (amd64) and macOS.

**Comment by maratori** [comment]
I added following workaround to my Dockerfile
```
# TODO: This is a workaround for bug in pkger library.
#       Info about files ui/app/build-bs/... is stored in json.
#       Content of the files are stored encoded with base64.
#       After that the whole json passed to filter, which replaces:
#        * home path -> $HOME
#        * go path -> $GOPATH
#        * go root -> $GOROOT
#       It means that if base64 encoded file contains `.../go...` it will be replaced with `...$GOPATH...`.
#       But it is invalid base64 string.
#       Workaround is to rename paths to reduce collision probability.
RUN ln -s /go /workaround_pkger_go_path && ln -s /root /workaround_pkger_home
ENV GOPATH /workaround_pkger_go_path
ENV HOME /workaround_pkger_home
```

**Comment by requaos** [comment]
@maratori @moqmar @ItalyPaleAle There is code in `master` to resolve this, but @markbates has not cut a new release version which includes this yet.
please test after `go get github.com/markbates/pkger@master` to see if the issue is resolved for you.
