### ISSUE TITLE
panic: gzip: invalid checksum

### ISSUE THREAD

**Issue by requaos** [markbates/pkger#26]
What did you do:
go install github.com/markbates/pkger/cmd/pkger
go mod download
pkger
go build .

What did you expect:
Application to initialize and read db migration scripts from pkged.go, in-memory

What happened:
```
seed_1    | 2019/11/11 03:34:13 exec: "go": executable file not found in $PATH: 
seed_1    | panic: gzip: invalid checksum
seed_1    | 
seed_1    | goroutine 1 [running]:
seed_1    | github.com/markbates/pkger.Apply(0x177dec0, 0x0, 0x1754ae0, 0xc000028a90, 0x0, 0x0)
seed_1    |     /go/pkg/mod/github.com/markbates/pkger@v0.11.0/apply.go:14 +0x155

**Comment by requaos** [comment]
Follow-up: The issue was encountered when using `golang:1.13-stretch` as a builder and copying the binary down into `debian:stretch-slim` container.

I switched to using `golang:1.13-alpine` for a builder and then copy down into a `alpine:3.10` container. The problem went away...

**Comment by markbates** [comment]
Can you please provide a reproducible example? Thanks.

**Comment by nlepage** [comment]
I also encountered the `panic: gzip: invalid checksum` at some point when running in a `gcr.io/distroless/static`.

After building again the same exact code and image, the problem disapeared, and now I can't reproduce it anymore...

**Comment by wayneashleyberry** [comment]
I also just started seeing this in some builds, will try get a repro together.

**Comment by requaos** [comment]
@markbates I have not been able to reproduce this issue with more recent versions of the library. Closing for now.

**Comment by advanderveer** [comment]
I've also run into this problem today.  I'm copying a binary, build on golang:alpine build image to a bare alpine image. With me too, it randomly started working again at some point. I was on the `v0.15.0` of pkger, but I don't think there is anything wrong with this library.  Looking at the previous issues it looks more like the binary code is not exactly portable, or at least causes a difference in the resulting gzip checksum sometimes?

**Comment by advanderveer** [comment]
I've now go this problem consistently on my mac, I've tried for over an hour now to isolate the problem to a certain file or line of code. But it stays elusive, removing a file from my repo or removing parts of the code (that sometines don't have anything to do with asset loading) will suddenly stop prevent the bug from happening. At this point I have to give up on this one, I will try to upload the full Docker container for someone else tonight, but my upload speed here is very slow so even that might not be feasible.

**Comment by alexpashkov** [comment]
We are also running into the issue, I thought there is something wrong with our setup, but seems like we are not the only ones

**Comment by sturfee-petrl** [comment]
@requaos  can you reopen please?

The same problem. I have files `.csv` , `proto` and `caffemodel` . It fails only if I include caffemodel. Without it works fine. 
>go: found github.com/markbates/pkger/cmd/pkger in github.com/markbates/pkger v0.15.1

The caffemodel in 20mb size. 
```
panic: gzip: invalid checksum

goroutine 1 [running]:
github.com/markbates/pkger.Apply(0x3af8f80, 0x0, 0x3adb3a0, 0xc0000207a0, 0x0, 0x0)
	/go/pkg/mod/github.com/markbates/pkger@v0.15.1/apply.go:12 +0x13a
```
@markbates

**Comment by requaos** [comment]
I still have v1.12.8 pinned to avoid this issue, and the really slow packaging. In my use case, I compile in a large directory of json and SQL files from a git submodule that our documentation team maintains that totals ~64Mb uncompressed.

**Comment by requaos** [comment]
For those that are still having this issue, please provide here a reproducible example. This will greatly assist the package maintainers

**Comment by sturfee-petrl** [comment]
@requaos Thank you!
Yes. Immediatelly after my initial message I was trying to get reproducible set up. 
1. Local machine 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
go version go1.14.3 linux/amd64
```
I couldn't reproduce the error. 
2. Server where I initially saw it
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
Docker image `nvidia/cudagl:9.0-devel-ubuntu16.04` with go1.14.2 on board
**what I saw**
First it's constantly failed if code included `.caffemodel`. 
Later it stills fail but on `.proto` file then with one of `.csv`. Then it started to work.  
_**how I reproduced it**_
I excluded files from embeding and recompiling it a lot of times. I constantly printed sizes of the files and content of txt ones to ensure that it read it correctly.

Sorry for late response. It was Friday and I got upset that there were not any robust result from me.

For now I removed all pkger code but I have git tag with the corresponding docker image. I will follow this issue.

**Comment by requaos** [comment]
@sturfee-petrl have you tried v0.12.8?

**Comment by sesposito** [comment]
I'm also seeing this issue. I've been trying to find a reliable way to reproduce it but unfortunately to no avail.

**Comment by zikaeroh** [comment]
I also just hit this in my first build using pkger:

```
$ docker run --rm -it hortbot/hortbot:r961.64c5a75 -h                            
Unable to find image 'hortbot/hortbot:r961.64c5a75' locally
r961.64c5a75: Pulling from hortbot/hortbot
24f0c933cbef: Already exists 
69e2f037cdb3: Already exists 
3c2cba919283: Already exists 
3fb3c9ab2331: Pull complete 
Digest: sha256:3c2615d5cf42c4ecf71406dd90f798194e94dd394f69694c295906b37bd15b28
Status: Downloaded newer image for hortbot/hortbot:r961.64c5a75
panic: gzip: invalid checksum

goroutine 1 [running]:
github.com/markbates/pkger.Apply(0x16c74a0, 0x0, 0x16962a0, 0xc000060700, 0x0, 0x0)
	/go/pkg/mod/github.com/markbates/pkger@v0.16.0/apply.go:12 +0x13a
main.init()
	/hortbot/pkged.go:12 +0x9f
```

The above image "reproduces" the behavior, but if it's non-deterministic in the build I'm not sure what I can do to truly reproduce it. It's a bummer to produce bad images... :(

**Comment by requaos** [comment]
Hi @markbates,

I found that the hepa filters were being applied after gzip. In certain circumstances the filters are modifying the body content of a gzip payload and will invalidate the payload checksum.

If you could please review this change to ensure that I am not missing the intention of these hepa filters.

**Comment by requaos** [comment]
I have been running my docker build on loop for the past 30 minutes without failure. With past versions `>v0.12.8`, this would have yielded a `panic: gzip: invalid checksum` by now.

@sturfee-petrl have you tried `v0.17.0`? I think this bug may be behind us. Please confirm.

**Comment by sturfee-petrl** [comment]
@requaos  I can try it later at this week.

**Comment by zikaeroh** [comment]
No luck, I now get this:

```
panic: illegal base64 data at input byte 569199

goroutine 1 [running]:
github.com/markbates/pkger.Apply(0x16c7540, 0x0, 0x16982a0, 0xc0001ce0f0, 0x0, 0x0)
	/go/pkg/mod/github.com/markbates/pkger@v0.17.0/apply.go:12 +0x13a
main.init()
	/hortbot/pkged.go:12 +0x9f
```

**Comment by zikaeroh** [comment]
I set up a fork and did a module replacement, where I removed the `hepa` replacement from the embed code (https://github.com/zikaeroh/pkger/commit/dceb832975ba87f6644e6b5fa8466d4999b9973b). No issues after that.

Is the `hepa` code required? It seems strange to indiscriminately replace things in the final JSON blob when those strings may be appearing for a good reason inside of things like the file bodies (or as substrings elsewhere). I can see how this might be affecting docker builds more often than user builds, as docker containers tend to have much shorter paths (my GOPATH is just `/go`, for example), but it seems pretty late to be doing that.

I'm going to try and extract the `pkged.go` file from a build with/without my patch to see what's getting replaced.

**Comment by zikaeroh** [comment]
I extracted the packaged JSON to take a look, and yeah, the replacement appears to be destructive to the data: https://gist.github.com/zikaeroh/d1ab20fe93cd38e3d851e6c75c1246c0

Since the characters in `/go` are all valid base64 characters, this replacement happens in the file data, like:

```
Xa5D2a7R37wbtfvwWda/$GOPATHrJ6Iiqs7NfJZ1Z/44Dd
```

This happens a few times, in addition to some metadata changes cases like:

```
"encoding$GOPATHb",
"github.com$GOPATH-chi/chi",
"github.com$GOPATH-chi/chi/middleware",
"github.com$GOPATH-redis/redis/v7",
"github.com$GOPATH-redis/redis/v7/internal",
```

If this sanitation needs to happen, I think it probably needs to happen much earlier in the process where it can target just path prefixes (a la `-trimpath` in the Go tool).

**Comment by qmuntal** [comment]
I'm also facing some sporadic `panic: illegal base64 data at input byte` after bumping to v0.17.0, but haven't been able to trace them yet.

**Comment by markbates** [comment]
The goal of the filters is to prevent leaking file system and env information in the meta data that’s packaged along with the file. 

It’s very possible they’re in the wrong place and need to be moved around a bit. 

They shouldn’t be sanitizing the files, just the meta data. 

--
Mark Bates

**Comment by requaos** [comment]
@markbates I will research method of slicing just the headers at the head of the gzip blob.

**Comment by requaos** [comment]
@markbates It looks like the best approach here is to use the filters inside the `mem` package, and also `pkging.NewFileInfo`, so that the exact values we want to mask with variables get swapped out on insert to the `*Pkger` object before marshalling to json.
I have started this effort.

**Comment by requaos** [comment]
@markbates This fix is kinda sloppy, but it gets the job done... Since now all of the replacements are string-based and get called much more frequently.

I would like to eventually convert the Purifier into a `strings.Replacer` object instance for performance reasons. What do you guys think?

**Comment by zikaeroh** [comment]
IMO a plain replacement seems a bit too lax. If the worry is GOPATH (an absolute path) ad others like GOBIN/PWD appearing in paths in the output, I would expect the check to be only prefix checks. E.g., if my GOPATH is `/go` (which it is in the standard docker Go images), I wouldn't expect metadata which contains `/go` somewhere in the middle to change, only `/go` or `/go/<stuff>`.

A comparison is `-trimpath` on the Go compiler, which operates on paths and only trims prefixes away; but it doesn't replace strings in the middle.

Right now, doing replacement anywhere in the strings leads to things like:

```
        "Module": {
          "Path": "github.com/hortbot/hortbot",
          "Main": true,
          "Dir": "/hortbot",
          "GoMod": "/hortbot$GOPATH.mod",
          "GoVersion": "1.13"
        }
```

I've only used pkger for a short time, so I don't know what all this metadata is used for in a real program that just wants to access the FS, though. Anything that makes the data not corrupt is good. :slightly_smiling_face:

**Comment by requaos** [comment]
@zikaeroh That is an excellent point. I will tag you on the PR for review once I make the change.

**Comment by requaos** [comment]
@zikaeroh I added Scrubbers to the hepa package that just replaces the string prefix if it exists.

**Comment by requaos** [comment]
@zikaeroh @sturfee-petrl @qmuntal @sesposito , we have decided to redact the hepa library for revision at a later date. Please be aware that the spirit of this library was for security, in that fully-qualified paths are embedded into the metadata of your static assets. If this behavior is undesirable, a preference is to build in a containerized environ, like docker, where the path strings is not exfiltrating data about your development environment.

Pending merge of #102

**Comment by maratori** [comment]
I added following workaround to my Dockerfile
```
# TODO: This is a workaround for bug in pkger library.
#       Info about files ui/app/build-bs/... is stored in json.
#       Content of the files are stored encoded with base64.
#       After that the whole json passed to filter, which replaces:
#        * home path -> $HOME
#        * go path -> $GOPATH
#        * go root -> $GOROOT
#       It means that if base64 encoded file contains `.../go...` it will be replaced with `...$GOPATH...`.
#       But it is invalid base64 string.
#       Workaround is to rename paths to reduce collision probability.
RUN ln -s /go /workaround_pkger_go_path && ln -s /root /workaround_pkger_home
ENV GOPATH /workaround_pkger_go_path
ENV HOME /workaround_pkger_home
```
